name: Sync Google Sheet to CSV
concurrency:
  group: insarag-sheet-sync
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 6,14,22 * * *"   # updates three times per day
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Google Sheet CSV
        run: curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vQ3qu-vdiZb7UWiI6MhgWBaWkkk431aRAzZ0CEcF5l3Djr650WYDn7k096xLjFfwGobrzzARlEBMlnU/pub?output=csv" -o usar_sites.csv

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add usar_sites.csv
          git diff --cached --quiet || git commit -m "Update dataset"
          git push
